import React from 'react';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Footer from '@/components/Footer';
import Navigation from '@/components/Navigation';
import '@/styles/globals.css';

// import
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Notion API with Next.js',
  description: 'Generated by create next app',
};

export const viewport = {
  width: 'device-width',
  initialScale: 1.0,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex-column flex h-screen w-screen`}>
        <div className="flex flex-col">
          <Navigation />
          <main className="flex flex-1 content-center items-center">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
