name: CI/CD Pipeline

on:
  push:
    branches:
      - 'week_*'  
      - main    
    tags:
      - 'v*'   
  pull_request:
    branches:
      - main  

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run format check
        run: npm run format

      - name: Run unit test
        run: npm run test

      - name: Check commit message
        uses: wagoid/commitlint-github-action@v6
        with:
          config: 'commitlint.config.cjs'

      - name: Create success file
        if: ${{ success() }}
        run: echo "CI passed" > ci-success.txt

      - name: Upload CI success artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: ci-success
          path: ./ci-success.txt

  deploy-preview:
    needs: ci
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - name: Download CI success artifact
        uses: actions/download-artifact@v4
        with:
          name: ci-success
      - name: Check CI success
        run: test -f ci-success.txt
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy to Vercel (Preview)
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}

  deploy-pre-production:
    needs: ci
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # 当推送到 main 分支时触发
    steps:
      - uses: actions/checkout@v4
      - name: Download CI success artifact
        uses: actions/download-artifact@v4
        with:
          name: ci-success
      - name: Check CI success
        run: test -f ci-success.txt
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=pre-production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy to Vercel (Pre-Production)
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

  deploy-production:
    needs: ci
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') 
    steps:
      - uses: actions/checkout@v4
      - name: Download CI success artifact
        uses: actions/download-artifact@v4
        with:
          name: ci-success
      - name: Check CI success
        run: test -f ci-success.txt
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy to Vercel (Production)
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}