# .github/workflows/production-deploy.yml
name: Production Deploy

on:
  push:
    tags:
      - 'v*'  # 只有符合 'v*' 格式的标签推送才会触发生产部署

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ensure Deployment is on Main Branch
        if: github.ref != 'refs/heads/main'
        run: |
          echo "Production deployment must be on main branch."
          exit 1

      - name: Download CI success artifact
        uses: actions/download-artifact@v4
        with:
          name: ci-success

      - name: Check CI success
        run: test -f ci-success.txt

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel (Production)
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}